load("//bzl/valdi:valdi_module.bzl", "valdi_module")

valdi_module(
    name = "layouts_demo",
    srcs = glob([
        "src/**/*.ts",
        "src/**/*.tsx",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/valdi_modules/src/valdi/valdi_core",
        "//src/valdi_modules/src/valdi/valdi_tsx",
        "//src/valdi_modules/src/valdi/valdi_navigation",
        "//apps/kitchen_sink/modules/common",
    ],
)
